### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by Rodolfo47** [Martinez-Gregorio-Hector/workflow_to_analysis_WES#17]
Hi Hector,
in general I agree whit your repo. The README file is understandable and the repo structure is fine

Specs

1.- In the general README.md pleas try to gib a brief introduction of the biological or clinical importance of the project. At this moment you only said that analyze whole-exome sequencing using some packages, but there are any kind of justification, research question or specific goals.

2.- In the `bin/README.md` you have some typos (ej: These subdirectories (plural), instead This subdirectory).
I think instead “If you don´t have reads in some formats” it must be read “The input files are located in ../data…
Concerning the script 5, I suggest modify the redaction with some thing like: “To run this script  the following files are needed, and must be located in `../data` …” I mean, you are indicating where can we get the files, but also we need put the files in the correct place in order to let the scrips find and use them.

3.- The file figure/ProblemLoopMutationalSignature.jpg is indeed a result? or what about them?

4.- Do your script 3 run? I think in lines 7 -12 you have some comments with out “#”. The same issue in scripts 4 and 5.
In R script 6 all the first lines (1-15) need be commented (put the # at the beginning of the line) and also some other text

5.- I think you and your parnas all ready solve the `bin/merged.sh` problems at class, can you pleas up date it?

**Comment by Rodolfo47** [comment]
Also remember check the evaluations [criteria](https://github.com/AliciaMstt/TallerBioinf/blob/master/Unidad1/listado_estudiantes.md) cause there are not a md file with the discussion
do not forget in the final repo version

**Comment by Rodolfo47** [comment]
Hi Hector,
I see you have already update some of the commentaries I do to improve your repo
I'm not sure that you attended every single one, but if I'm mistake, pleas let me know (as soon as possible) and I'll correct the evaluation

1.- General README.md:
R: You do the corrections

2.- Typos and redaction in bin/README.md:
R: You delete the bin/README.md, why?
So I can't see the suggested modifications nor in the bin/README.mb neither in the inner script 5 comments.

3.- What about figure/ProblemLoopMutationalSignature.jpg?:
R: What about them?
You do not respond the question and just delete the file...

4.- ## in scripts 3, 4 and 5:
R: You do the corrections

5.- merged.sh update:
R: You do the corrections

6.- Discussion.md:
R: You do not made the Discussion.md file

**Comment by Martinez-Gregorio-Hector** [comment]
Hi Rodolfo

Thank you for your comments. 

Point 2. I modified  it **"2.- Typos and redaction in bin/README.md"**  because Alicia suggested me
**Your main README has to include a short description of each of the scripts in bin. This information is mentioned in the README inside bin, but without opening bin there is no way of knowing this. Therefore you should either have only one README with all the information, or in your main README mention that bin contains a second README describing what the scripts do (and link to it)** and i did the recommendations in this point **you should either have only one README with all the information**.

Point 3. **What about figure/ProblemLoopMutationalSignature.jpg?** was only an example of an issue however I thought that it was not necessary, so I eliminated it. You can check the issue and it was not mentioned. This is the link of my (issue)[https://github.com/Martinez-Gregorio-Hector/workflow_to_analysis_WES/issues/9].

Point 6. This can be found (here)[https://github.com/Martinez-Gregorio-Hector/workflow_to_analysis_WES/blob/master/Repo_Abstract_and_Discussion.md]

**Comment by Rodolfo47** [comment]
ok
thanks for answer and clarify the points
and for make the discussion file

**Comment by Rodolfo47** [comment]
close
